### ISSUE TITLE
 ERR PuppetWebBridge init() exception

### ISSUE THREAD

**Issue by sowhatwill** [Chatie/wechaty#1018]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

 centos7.3 

### Expected behavior

Starting Wechaty v0.13.37 with Node.js v8.9.1 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended on your bot script.
Executing babel-node --presets env mybot.js
08:45:54 WARN Wechaty init() DEPRECATED and will be removed after Jun 2018. Use start() instead.
08:45:54 INFO Wechaty v0.13.32 starting...
08:45:54 ERR PuppetWebBridge init() exception: Error: spawn EACCES
08:45:54 ERR PuppetWeb initBridge() exception: spawn EACCES
08:45:54 WARN PuppetWebBridge quit() page.close() exception: TypeError: Cannot read property 'close' of undefined
08:45:54 WARN PuppetWebBridge quit() browser.close() exception: TypeError: Cannot read property 'close' of undefined
08:45:54 ERR PuppetWeb init() exception: Error: spawn EACCES
08:45:54 ERR Wechaty start() exception: spawn EACCES
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn EACCES
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
