### ISSUE TITLE
ERR PuppetWebBridge init() exception: Error: connect ECONNREFUSED 127.0.0.1:35493

### ISSUE THREAD

**Issue by dj940212** [Chatie/wechaty#1113]
### Provide Your Network Information
AliYun Ubuntu 14.04   node v8.5.0

### Full Output Logs

INFO Wechaty v0.13.72 starting...
22:14:49 ERR PuppetWebBridge init() exception: Error: connect ECONNREFUSED 127.0.0.1:35493
22:14:49 ERR PuppetWeb initBridge() exception: connect ECONNREFUSED 127.0.0.1:35493
22:14:49 WARN PuppetWebBridge quit() page.close() exception: TypeError: Cannot read property 'close' of undefined
22:14:49 WARN PuppetWebBridge quit() browser.close() exception: TypeError: Cannot read property 'close' of undefined
22:14:49 ERR PuppetWeb init() exception: Error: connect ECONNREFUSED 127.0.0.1:35493
22:14:49 ERR Wechaty start() exception: connect ECONNREFUSED 127.0.0.1:35493
(node:23003) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:35493
(node:23003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment]
Please try the latest code and it might solve this issue.
