### ISSUE TITLE
OK to add a .eslintrc.js file?

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty#1120]
I found that the wechaty doesn't have a `.eslintrc.js` file. Would it be OK for me to add one, since nobody is using it? 

The content would be like
https://gist.github.com/suntong/3a2a1c8b10609a9d5080f289355ff09b

If so, I'll put into PR for #1100.

cheers

**Comment by zixia** [comment]
Thanks for your suggestion.

However, I think it's not necessary to add a `.eslintrc.js` because all Wechaty is written in TypeScript. We should use `tslint` with `tslint.json` instead.

And of course, if you are using Wechaty as a dependency for your project, you can add `.tslintrc.js` to your project root directory as well. ;)

**Comment by suntong** [comment]
sure.
