### ISSUE TITLE
how to use wechaty-bro.js

### ISSUE THREAD

**Issue by Zhou-Bill** [Chatie/wechaty#1148]
how to use wechaty-bro.js

i have try to inject the javascript (wechaty-bro.js) into https://wx.qq.com/ ，but some error has occurred;

like: 
![image](https://user-images.githubusercontent.com/13554001/38483807-cbf1b790-3c06-11e8-8a19-bb9e7b23fa69.png)

**Comment by zixia** [comment]
If I understand you right: you want to build a new UI for Wechat powered by Wechaty totally from scratch?

Then I'd like to suggest you just run Wechaty from the standalone mode(which is the default, using puppeteer headless mode), then you will be able to use all the Wechaty API to do whatever you want.

To answer your question: you can not inject the `wechaty-bro.js` to your browser directly, because it is highly coupled with the puppeteer in the current Wechaty code base.

Please let me know if you have any other question.

Good luck!

**Comment by Zhou-Bill** [comment]
yes, so i just need to `npm install wechaty` to use wechaty in  electron ?

**Comment by zixia** [comment]
Yes, I think so.

Please feel free to let me know if you have any other questions.

**Comment by Zhou-Bill** [comment]
thanks

**Comment by zixia** [comment]
Could you please close this issue if your issue is solved?

**Comment by zixia** [comment]
I'll close this issue due to inactivity for more than one month.
