### ISSUE TITLE
Why does the message's creation time and id not be attributed to the Message instance?

### ISSUE THREAD

**Issue by lvxuan263** [Chatie/wechaty#1195]
In the v0.15 version, the Message instance cannot access the obj attribute. obj and rawObj belong to the puppet underlying data and are not extracted to the upper layer. How do I get the message create time and message id?

**Comment by zixia** [comment]
According to the new design of the Wechaty v0.16(which v0.15 is the development branch of 0.16), you will not be able to access the underlying data of the Puppet any more.

The reason of this is because we need to abstract the `Message` to de-couple with the specific `Puppet`.

The solution would be:

1. Use v0.14 instead, or
1. Read the code and find a way to do it. (and any valuable proposal is welcome)

**Comment by lvxuan263** [comment]
Thank you very much for your reply. I will close this issue.
 
Best regard.

**Comment by zixia** [comment]
You are welcome.

**Comment by zixia** [comment]
See #1200
