### ISSUE TITLE
请问怎么添加微信群中的人当做自己的好友呢 有例子可以参考吗

### ISSUE THREAD

**Issue by checkblue** [Chatie/wechaty#1207]

**Comment by zixia** [comment]
Hello, thank you for using Wechaty. 

Issues are about to fire bugs & request features only, so it's not a Support Forum.

To get help, ask questions and discuss with other developers, please join our _Wechaty Developers' Home_ community in Wechat.

### Join Wechaty Developers' Community

Wechaty is used in many ChatBot projects by hundreds of developers. If you want to talk with other developers, just scan the following QR Code in WeChat with secret code _wechaty_, you can join our **Wechaty Developers' Home** at once.

![Wechaty Developers' Home](http://chatie.github.io/wechaty/images/bot-qr-code.png)

Scan now, because other Wechaty developers want to talk with you too! (secret code: _wechaty_)
