### ISSUE TITLE
m.say() repeat many many times

### ISSUE THREAD

**Issue by Ramonywangziyao** [Chatie/wechaty#1216]
when i call m.say(), it kept sending out lots of same msg blows up the receiver. what is wrong? 
thanks

**Comment by ken-talkingsource** [comment]
如果你寫一個類似回音的功能，要在啟動後紀錄自己的 id，並在訊息回覆前過濾掉。

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by Ramonywangziyao** [comment]
in .on('message', async m => {
    m.say('hi')
})

when is is called after receiving a message, it sends out tons of 'hi' to the sender, only stop if i shut it down or the server stopped responding. 

i used npm for installing wechaty, tried both the newest version as well as @0.14

thanks!

**Comment by suntong** [comment]
your account didn't get blocked for that @Ramonywangziyao? Amazing...

**Comment by zixia** [comment]
Close this issue because it's answered, and inactivity for 60 days.
