### ISSUE TITLE
自动回复语音（AMR文件）

### ISSUE THREAD

**Issue by zhoumh1988** [Chatie/wechaty#1281]
我想自动回复时候回复语音文件，而不是让用户去下载文件，请问具体如何实现。
我看了很多issue，没找到符合的。
尝试了用MediaMessage，不过提示
```console
no MIME Type found on mediaMessage: *.amr
```
请问是我哪里设置的不对吗？
下面是我写的代码
```javascript
let FILE = path.resolve(__dirname, './file/' + content + '.amr');
await m.say(new MediaMessage(FILE));
```

**Comment by zixia** [comment]
1. I'm not sure the `.amr` type is supported by web wechat API. You can try to send the file via the browser and see if it could work.
2. web wechat API cannot send audio that can be directly played instead of download.
3. Other Puppet might be able to support your requirement, you can watch the latest progress of the PuppetPadchat, PuppetIosCat, etc.

**Comment by zixia** [comment]
Merge to #1300 

Please test it with the latest v0.15 master branch if you are interested.

**Comment by zhoumh1988** [comment]
ERR PuppetPuppeteer sendMedia() exception: no MIME Type found on mediaMessage: test.amr
0|mybot    | Error: no MIME Type found on mediaMessage: test.amr

cannot support it
