### ISSUE TITLE
still restart

### ISSUE THREAD

**Issue by shijianzhong** [Chatie/wechaty#1378]
nodemon] restarting due to changes...
[nodemon] starting `node bin/www`
06:06:26 WARN Wechaty on('friend', contact, friendRequest) is DEPRECATED. use on('friendship', friendship) instead
06:06:26 INFO Wechaty start() v0.16.5 is starting...
06:06:26 INFO Wechaty initPuppet() using puppet: puppeteer

**Comment by shijianzhong** [comment]
nodemon] restarting due to changes...
[nodemon] starting `node bin/www`
06:06:26 WARN Wechaty on('friend', contact, friendRequest) is DEPRECATED. use on('friendship', friendship) instead
06:06:26 INFO Wechaty start() v0.16.5 is starting...
06:06:26 INFO Wechaty initPuppet() using puppet: puppeteer

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.

**Comment by shijianzhong** [comment]
okay,thanks
