### ISSUE TITLE
I changed my operating system，but when run dev ,still output restarting

### ISSUE THREAD

**Issue by shijianzhong** [Chatie/wechaty#1382]
### Provide Your Network Information

1.北京beijing
1. Aliyun

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:
[root@izvkxk91ybsenaz wechatserve]# npm run dev

> koa2test@0.1.0 dev /root/wxserve/source/wechatserve
> nodemon bin/www

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/www`
06:06:19 WARN Wechaty on('friend', contact, friendRequest) is DEPRECATED. use on('friendship', friendship) instead
06:06:19 INFO Wechaty start() v0.16.5 is starting...
06:06:19 INFO Wechaty initPuppet() using puppet: puppeteer
请扫描二维码完成登录: 
[nodemon] restarting due to changes...
[nodemon] starting `node bin/www`


```
</details>

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
