### ISSUE TITLE
PuppetPadchat:Can't get user's City.

### ISSUE THREAD

**Issue by zhoumh1988** [Chatie/wechaty#1390]
version 0.17.24

```javascript
on('message', message => {
    let sender = message.from();
    console.log(sender.rawObj.City);
})
```

I want to get user's default locate info.Like City,Province,Area.
I got these before version 0.15,but cannot now.

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zhoumh1988** [comment]
@zixia
 I have perfected the question.
On version 0.14.10 , I can get city Information of sender.

`
sender.rawObj.City
`

**Comment by zixia** [comment]
You should use `sender.city()` method instead.

**Comment by zhoumh1988** [comment]
tks,it works.

**Comment by zixia** [comment]
Could you please close this issue then?
