### ISSUE TITLE
why friendship.contact().name() is ""

### ISSUE THREAD

**Issue by Zhou-Bill** [Chatie/wechaty#1490]
wechaty version: v0.19.18

the code as below:
![image](https://user-images.githubusercontent.com/13554001/42863522-1dbf3c90-8a96-11e8-9ae8-834b9f01becc.png)

and the result is 

![image](https://user-images.githubusercontent.com/13554001/42863565-3ea30b3a-8a96-11e8-94e8-f05a36d5b2a8.png)

you can see friendship.contact().name() is ""?

**Comment by Zhou-Bill** [comment]
i use 0.19.18 yesterday, it is normal, but today the name is "" .
i  try it in 0.19.21 , the result is same as v0.19.18.

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by Zhou-Bill** [comment]
when i test auto add friends ,  it sometime has contact's name, but sometime the name is empty.
i saw it in `contact.js`, i thing `this.payload` is null.

you can test it in  by console.log(friendship.contact().name()) when you **receive friends request** or **Comfirm Friend** after a few minutes ....

**Comment by zixia** [comment]
@Zhou-Bill Did your issue resolved? What's the problem cause this?

**Comment by Zhou-Bill** [comment]
@zixia  No, I think i  should create new Issues in padchat . do you have the same problem?

**Comment by zixia** [comment]
Yes, if you believe this is related with padchat, create it over there is better.

I did not have this problem because recently I have not used this API. I believe other developers can know more information than me.
