### ISSUE TITLE
Wechaty Puppet Ioscat Testing:  iPhone(iOS) Wechat Hooking Support are comming!

### ISSUE THREAD

**Issue by huan** [Chatie/wechaty#1530]
Hello to developers who are using Wechaty,

We have excellent news for you: **Wechaty Puppet Ioscat which supporting iPhone(iOS) Wechat Hooking, is going to ready for testing!**, and Alpha Testing Volunteers are open to applications now.

If you want to be an early bird for the Puppet Ioscat, and cannot wait for the Beta release, then you are welcomed to apply for joining the v0.19 Alpha Tester List!

[![Wechaty](https://chatie.io/wechaty/images/wechaty-logo-en.png)](https://github.com/chatie/wechaty)

Start from today; we need some volunteers who are interested in joining the alpha testing, for example, our new Ioscat Wechat Puppet which backed by the iPhone App Hooking. If you are one of them, please leave a comments under this issue,  introduce yourself about who you are and what you want to do(please DO follow the following TEMPLATE and fill it in details, or you might not be able to be selected), so that we can be able to add you to the alpha testers list if you are qualified.

### Wechaty Ioscat Puppet Alpha Tester Apply Template

-----------
### 9. I understand that the Puppet Ioscat is in very _Early Alpha Stage_, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)

-----------

Looking forward to hearing back from you, and please submit a new issue if you found any bug or have any feature requests for Wechaty. PR is also welcome with an issue submitted first.

At last, I'd like to say thank you to @lijiarui @linyimin, who are the main contributors to the ioscat puppet. it will not possible to go out without your help; it's our teamwork!

Learn more about the Puppet Ioscat at #1528 

Have a good weekend!

Best,
Huan

**Comment by kis87988** [comment]
1. Introduce Yourself(who you are):
    A student group manager and student
2. Explain the Problem You Want to Solve:(what you do):
    wechat groups, and manage group. send some info to student and stats analysis
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
   No
4. Your Email:
    kis87988@gmail.com
5. Your Wechat:
    kis87988
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: 
    (Please join the group if you are not, and then say YES at here)
    Yes
7. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
    Yes

William

**Comment by JesseWeb** [comment]
1. Introduce Yourself(who you are):
   normally developer
2. Explain the Problem You Want to Solve:(what you do):
   file center
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
   NO
4. Your Email:
   395731482@qq.com
5. Your Wechat:
   xyzcain
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
   YES
7. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
   YES

**Comment by solarhell** [comment]
1.Introduce Yourself:
solarhell (backend developer)

2.Explain the Problem You Want to Solve:
Manage groups programmingly.

3.Are Your Bot Related with the Following Tasks?
Gambling
Adult & Sex

NO

4.Your Email:
songjiaxin2008@gmail.com

5.Your Wechat:
CrsPrince

6.I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md:
YES

7.I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support:
YES, solarhell.

**Comment by Arvintian** [comment]
Introduce Yourself(who you are): software developer

Explain the Problem You Want to Solve:(what you do): Integrate wechaty to work flow.

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks?  NO 

Your Email: arvintian8@163.com

Your Wechat: tian17865933200

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: YES

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES

**Comment by chatch** [comment]
Introduce Yourself(who you are): Decentralised Apps developer building with Stellar, Mobius, Ethereum

Explain the Problem You Want to Solve:(what you do): Build a tip bot for Mobius. Similar to this one for telegram: https://github.com/mobius-network/mobius-tipbot-ruby but build it for Wechat/微信 users.

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? NO

Your Email: hatch@tuta.io

Your Wechat: wxid_39uww6xwmfso22

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: YES - in the second room.

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES

**Comment by wuying8** [comment]
Introduce Yourself(who you are): 
WeChat product developer

Explain the Problem You Want to Solve:(what you do):
Mainly responsible for the development of WeChat group products

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? NO

Your Email: 86824400@qq.com

Your Wechat: xingxio007

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md:
YES

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES

**Comment by zhaizong** [comment]
@kis87988 @fidonium @JesseWeb @solarhell @wuying8 @chatch @Arvintian Your applications are approved. Please check your email inbox for the next steps.

Welcome!

**Comment by shijunti19** [comment]
Introduce Yourself(who you are):
WeChat product developer

Explain the Problem You Want to Solve:(what you do):
Mainly responsible for the development of WeChat group products

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? NO

Your Email: 527528007@qq.com

Your Wechat: meinvyifei

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md:
YES

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES

**Comment by JieJiSS** [comment]
Introduce Yourself(who you are):
A high school student in Beijing
Explain the Problem You Want to Solve:(what you do):
Need to set up a bot to manage groups & contacts, including but not limited to accepting friend requests, sending texts & images, 
Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
NO
Your Email:
jiejiss@outlook.com
Your Wechat: 
13801391007
I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md:
(Please join the group if you are not, and then say YES at here)
YES
I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
YES, Jeffrey

**Comment by softwarezhu** [comment]
introduce Yourself(who you are):
Wechaty Developer

Explain the Problem You Want to Solve:(what you do):
Manage groups, contacts, auto reply...

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
No

Your Email:
419128626@qq.com

Your Wechat:
software_zhu

I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO)
YES

I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO)
Yes

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
YES

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
YES, Piggy

**Comment by uz5m** [comment]
introduce Yourself(who you are):
A developer of a startup

Explain the Problem You Want to Solve:(what you do):
I need a robot to manage my customers in wechat and autochat with them

Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
No

Your Email:
txj_killer@163.com

Your Wechat:
uz5m00

I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO)
YES

I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO)
Yes

I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
YES

I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
YES, uz5m

**Comment by falost** [comment]
1. Introduce Yourself(who you are): Front-end development
2. Explain the Problem You Want to Solve:(what you do): Management group, inviter plus group
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO) no
4. Your Email: falost.cc@gmail.com
5. Your Wechat: ishengun
6. I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO) yes
7. I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO) yes 
8. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md:  (Please join the group if you are not, and then say YES at here)  yes
9. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here) yes

**Comment by yanguoyu** [comment]
1. Introduce Yourself(who you are): Front-end development
2. Explain the Problem You Want to Solve:(what you do): try to create wechat group manage
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO): no
4. Your Email: 841185308@qq.com
5. Your Wechat: lengyue292457
6. I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO) yes
7. I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO) yes
8. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here) yes
9. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here) yes

**Comment by seanxlliu** [comment]
### 1. Introduce Yourself(who you are): CTO of a startup
### 2. Explain the Problem You Want to Solve:(what you do): Natural language
### 3. Are Your Bot Related with any of the _Gambling_, _Adult/Sex_ Tasks? (YES/NO) No
### 4. Your Email: little_deer@hotmail.com
### 5. Your Wechat: xiaolu79425
### 6. I Had Read the Tutorial at [PuppetIoscat usage](https://github.com/linyimin-bupt/wechaty-puppet-ioscat/wiki/PuppetIoscat-usage) in Detail: (YES/NO) YES
### 7. I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO) YES
### 8. I Had Joined the _Wechaty Developers' Home_ Wechat Room by Scan QRCode from [README.md](https://github.com/Chatie/wechaty#join-us): (Please join the group if you are not, and then say YES at here) YES
### 9. I understand that the Puppet Ioscat is in very _Early Alpha Stage_, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here) YES

**Comment by lijiarui** [comment]
Sorry all, we haven't published this puppet yet for some reason, please move to https://github.com/Chatie/wechaty/issues/1668

I will reopen this issue when we launch this puppet.

Thanks!

**Comment by abczise** [comment]
1. Introduce Yourself(who you are):
    Middle school students who like robot development
2. Explain the Problem You Want to Solve:(what you do):
    Development of Virtual Artificial Intelligence Robot
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO)
    NO
4. Your Email:
    abczise@qq.com
5. Your Wechat:
    czsgtxy
6. I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO)
    yes
7. I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO)
   yes
8. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
   yes
9. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
  yes

**Comment by unclemin** [comment]
1. Introduce Yourself(who you are): 前端开发
2. Explain the Problem You Want to Solve:(what you do):尝试创建微信群
3. Are Your Bot Related with any of the Gambling, Adult/Sex Tasks? (YES/NO) 否
4. Your Email:571590938@qq.com
5. Your Wechat:18188348621
6. I Had Read the Tutorial at PuppetIoscat usage in Detail: (YES/NO)是
7. I Had Prepared the Required Jailbreak iPhone with the Required Software Installed: (YES/NO)是
8. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: 是(Please join the group if you are not, and then say YES at here)
9. I understand that the Puppet Ioscat is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)

**Comment by su-chang** [comment]
@unclemin Sorry to say that this Testing has already closed, if you are interest in Windows WeChat Hook, please see: https://github.com/wechaty/wechaty/issues/1941
