### ISSUE TITLE
不能通过群成员添加好友

### ISSUE THREAD

**Issue by bopro** [Chatie/wechaty#1578]
```
const memberList = await room.memberList()
for (let i = 0; i < memberList.length; i++) {
  await bot.Friendship.add(member, 'Nice to meet you! I am wechaty bot!')
}
```

看到bot.Friendship.add方法是使用了searchContact函数，获取v1,v2进行好友添加。

但是获取的群成员的wxid是wxid_开头的都搜索不到好友，只有wxid非wxid_开头的才可以正常添加。

经过测试，多数成员的wxid虽然是wxid_开头，但是他们有微信号, 通过微信号使用searchContact就可以正常添加。不知道bot.Friendship.add时能不能获取微信号呢？

**Comment by lijiarui** [comment]
1. Yes, all contact begins with `wxid_` cannot be added successfully, this is known.
2. In the future, we may add a function to get real wechat id. but not sure whether can be searched by `searchContact ` 
3. Please move this to https://github.com/lijiarui/wechaty-puppet-padchat because this is related to wechaty-puppet-padchat instead wechaty.

**Comment by lijiarui** [comment]
@bopro Do you have more question about this issue?

**Comment by lijiarui** [comment]
Close this issue due to long time no reply.

**Comment by zhouyu1993** [comment]
Web, PuppetPuppeteer,

`bot.Friendship.add` doesn't work.

**Comment by cleverphp** [comment]
lijiarui，你是女的吗？好美啊，可以认识下吗？

**Comment by JarVZhao** [comment]
bot.Friendship.add doesn't work. And contact begins without wxid_.
