### ISSUE TITLE
调用发消息接口后，emit 出的消息事件对应的消息时间不正确

### ISSUE THREAD

**Issue by zhaokefei** [Chatie/wechaty#1617]
![image](https://user-images.githubusercontent.com/16509241/46645992-3fd3c980-cbba-11e8-93d9-3e4fe4dd9548.png)

**Comment by lijiarui** [comment]
Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, and help other developers to search, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

Also, please **paste the full log instead of the log picture**

I'll close this issue. Please re-submit a new issue to provide the information that needed.
