### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by crdsoft** [Chatie/wechaty#1656]
async function onMessage (msg) {
  console.log(msg.toString())
  let msgText = msg.text()
  if (msgText.indexOf("vip")  > -1) {
        respText = "想成为VIP？"
        await msg.say(respText)
    }
}

微信端收到乱码：
���ΪVIP��

怎么解决？

**Comment by crdsoft** [comment]
@lijiarui 帮忙看看呗

**Comment by crdsoft** [comment]
需要什么信息？我发你。

**Comment by lijiarui** [comment]
Please follow the **ISSUE Template** ：

### 0. Report Issue Guide

0. Please search in the issue first, and make sure your problem had not been reported before.
1. If your issue is related to _wechaty-puppet-padchat_, please report the issue at <https://github.com/lijiarui/wechaty-puppet-padchat/issues/new>
2. If your issue is related to _wechaty-puppet-puppeteer_, please report the issue at <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/new>
3. If your issue is DIRECT related to Wechaty, then please follow the below template and make sure you fill it as required in detail.

### 1. Expected behavior

**Question: What behavior do you expect?**

Answer:

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer:

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by crdsoft** [comment]
@lijiarui 美女

**Comment by lijiarui** [comment]
Please paste the full log info, thanks ：）

**Comment by lijiarui** [comment]
Could you add `console.log(respText)` as the following showed and have a try?

```diff
async function onMessage (msg) {
  console.log(msg.toString())
  let msgText = msg.text()
  if (msgText.indexOf("vip")  > -1) {
        respText ='想成为VIP？'
+      console.log(respText)
        await msg.say(respText)
    }
}
```

**Comment by crdsoft** [comment]
改成上面代码，结果运行出错了
Contact<义鉑> login
Message#Text(🗣Contact<公安信息化>👤Contact<义鉑>)<vip>
(node:16956) UnhandledPromiseRejectionWarning: ReferenceError: respText is not defined
    at Wechaty.onMessage (C:\Users\Administrator\wechaty\examples\starter-bot.js:32:20)
    at Wechaty.on.args (C:\Users\Administrator\wechaty\node_modules\wechaty\dist\src\wechaty.js:383:26)
    at Wechaty.emit (events.js:182:13)
    at Wechaty.EventEmitter.emit (domain.js:441:20)
    at Wechaty.emit (C:\Users\Administrator\wechaty\node_modules\wechaty\dist\src\wechaty.js:179:22)
    at Wechaty.<anonymous> (C:\Users\Administrator\wechaty\node_modules\wechaty\dist\src\wechaty.js:477:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\wechaty\node_modules\wechaty\dist\src\wechaty.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:16956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by crdsoft** [comment]
就是改成这样也是两行错误编码
async function onMessage (msg) {
  console.log(msg.toString())
 let msgText = msg.text()
  if (msgText.indexOf("vip")  > -1) {
      let  respText ='想成为VIP？'
        console.log(respText)
        await msg.say(respText)
        await msg.say('甚至将他的')
    }
}

运行结果：
Contact<义鉑> login
Message#Text(🗣Contact<公安信息化>👤Contact<义鉑>)<vip>
���ΪVIP��
Message#Text(🗣Contact<义鉑>👤Contact<公安信息化>)<���ΪVIP��>
Message#Text(🗣Contact<义鉑>👤Contact<公安信息化>)<����������>

**Comment by lijiarui** [comment]
Could you just try the following code:
```ts
const a = '中文'
console.log(a)
```

If this still has a strange code, I guess this is not related to wechaty, it is related to your code editor.

**Comment by windmemory** [comment]
Or related to windows encoding.

**Comment by crdsoft** [comment]
解决了，谢谢美女和大神。果然是编辑器问题，我直接使用记事本的原因。
