### ISSUE TITLE
关于win7安装 npm install wechaty-puppet-padpro 的问题

### ISSUE THREAD

**Issue by cuiweipeng** [Chatie/wechaty#1716]
🚨 The issue tracker is not for questions 🚨
你好，这个安装的时候 报错

**Comment by lijiarui** [comment]
Important：Please file the issue follow the template, or we won't help you to solve the problem.
I will close this issue, feel free to file a new issue with the issue template.


## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Steps to reproduce the behavior:
1. run '...'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.


## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context
Add any other context about the problem here.

[bug]

**Comment by cuiweipeng** [comment]
感谢回复，我用 ubuntu了。。  window的确不好安装。。

**Comment by cuiweipeng** [comment]
> ## Important：Please file the issue follow the template, or we won't help you to solve the problem.
> I will close this issue, feel free to file a new issue with the issue template.
> ## 0. Report Issue Guide
> 1. Please run the following command and check whether the problem has been fixed：
> 
> ```
> rm -rf package-lock.json
> rm -rf node_modules
> npm install
> ```
> 1. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.
> 2. Please search in the issue first, and make sure your problem had not been reported before
> 
> ## 1. Versions
> * What is your wechaty version?
>   Answer:
> * Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
>   Answer:
> * What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
>   Answer:
> * What is your node version? (run `node --version`)
>   Answer:
> * What os are you using
>   Answer:
> 
> ## 2. Describe the bug
> Give a clear and concise description of what the bug is.
> 
> ## 3. To Reproduce
> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.
> 
> Steps to reproduce the behavior:
> 
> 1. run '...'
> 2. ...
> 3. ...
> 
> ## 4. Expected behavior
> Give a clear and concise description of what you expected to happen.
> 
> ## 5. Actual behavior
> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.
> 
> ## 6. Full Output Logs
> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)
> 
> **We need full log instead of log screenshot or log fragments!**
> 
>  Show Logs
> ## 7. Additional context
> Add any other context about the problem here.
> 
> [bug]

感谢回复，我用 ubuntu了。。 window的确不好安装。。
