### ISSUE TITLE
Wechaty v0.26 iosBird Testing, an iOS hook puppet implementation!

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty#1775]
Hello to developers who are using Wechaty,

We have excellent news for you: Wechaty New Puppet System is going to ready for testing!, and Alpha Testing Volunteers are open to applications now.

We have launched a new puppet `wechaty-puppet-iosbird` few weeks ago, now we are launching alpha test for `wechaty-puppet-iosbird`.

New puppet `wechaty-puppet-iosbird` is a solution that take advantage of jailbroken iPhone, hook the `WeChat` application in it, send the data to a transit server via websocket, then `wechaty` user could connect the transit server to manipulate `WeChat`.

This solution costs higher than the other puppets, and has the most complicate setup procedure so far. However, since this is connecting `WeChat` directly in the phone, there are some advantage for this solution over all the others:

* Never need to scan the QR code
* Potentially is the puppet that supports all the `WeChat` functions
* You can connect to the account with `wechaty-puppet-iosbird` and `wechaty-puppet-padchat` at the same time
* Unless the account is block by `WeChat`, you never need to re-login

Start from today; we need some volunteers who are interested in joining the alpha testing. If you are one of them, please leave a comments under this issue, introduce yourself about who you are and what you want to do(please DO follow the following TEMPLATE and fill it in details, or you might not be able to be selected), so that we can be able to add you to the alpha testers list if you are qualified.

#### Install

```shell
npm install wechaty
npm install wechaty-puppet-iosbird
```

#### Example

```ts
import { Wechaty }        from 'wechaty'
import { PuppetIosbird }  from 'wechaty-puppet-iosbird'

const puppet = new PuppetIosbird()

const bot = new Wechaty({
  puppet,
})

// 设置完成

// 运行 wechaty
bot
.on('login',            user => console.log(`User ${user} logined`))
.on('message',       message => console.log(`Message: ${message}`))
.start()
```

see more: https://github.com/botorange/wechaty-puppet-iosbird
contact: 
![](https://github.com/botorange/wechaty-puppet-padpro/raw/master/image/contact.gif)

### Wechaty Puppet iosBird Alpha Tester Apply Template
---
#### 3. Are Your Bot Related with the Following Tasks? (YES/NO)
* Gambling
* Adault & Sex
#### 7. I understand that the `wechaty-puppet-iosbird` is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)

**Comment by caffreycc** [comment]
1. Introduce Yourself(who you are):
**Caffrey work in CATPARTY，Node Development Engineer**
2. Explain the Problem You Want to Solve:(what you do):
**Wechat Group Management**
3. Are Your Bot Related with the Following Tasks? (YES/NO)
**NO**
4. Your Email:
**001@mxclass.com**
5. Your Wechat:
**Richachen_2013**
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
**YES**
7. I understand that the wechaty-puppet-iosbird is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
**YES**

**Comment by icmpv6** [comment]
1. Introduce Yourself(who you are): **Freelancer, Software Architect/Consultant**
2. Explain the Problem You Want to Solve:(what you do): **Process Management via WeChat**
3. Are Your Bot Related with the Following Tasks? (YES/NO): **NO**
Gambling
Adault & Sex
4. Your Email: **felix@lomoc.com**
5. Your Wechat: **finock**
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here) **YES**
7. I understand that the wechaty-puppet-iosbird is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here) **YES, Felix**

**Comment by lijiarui** [comment]
Close this since we deprecated this project.
