### ISSUE TITLE
Keep emoji characters from user name and room name

### ISSUE THREAD

**Issue by sinofool** [Chatie/wechaty#207]
According to issue #64 , emoji characters are removed from user name and room name for searching.
But these characters are also important for displaying.
Please keep the original name or have a different field store the real name.

**Comment by JasLin** [comment]
by now,you can use ```get('name')``` to workaround this

**Comment by zixia** [comment]
To keep the emoji characters is sometimes complicated because there are many emoji kinds, sometimes they are Unicode Character, sometimes they are BBCode like `[laugh]` and sometimes they are XML.

If we want to keep the emoji, then we have to discuss them in details and make a proposal for that.

And yes, the original data is stored in the contact.RawObj, please feel free to hack that data.

**Comment by zixia** [comment]
It seems we have a workaround for this issue, and it's hard to decide which character should be kept in the name().

Close this issue now, please let me know if there are any good solutions to suggest.
