### ISSUE TITLE
[new feature] add function message.mention()

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#216]
In order to let the bot and his contact chat in the room, maybe we could add a "@" event, when others @bot then the bot knows and do something.

**Comment by zixia** [comment]
Need to be proposed with more details of the design.

And also should describe the **Problem** and discuss the **Solution** in your thought.

**Comment by lijiarui** [comment]
Well, I PR a solution, what do you think about it?

I added an event called 'message-at', and the following code works well.

``` ts
.on('message-at', function(contact, room, content) {
  console.log('message-at event works!')
  console.log(contact)
  console.log(room)
  console.log(content)
  })
```

**Comment by zixia** [comment]
Before PR, please discuss about the design here first.

A new event maybe is not needed because that will duplicate the message event, which might not necessary.

**should describe the Problem and discuss the Solution in your thought.**

**Comment by lijiarui** [comment]
It dose duplicate the message event, or it is belong to the message event.     

Well, actually, all the event duplicate the message event, but it is convenience to differentiate them.  

I found you are going to add a function to mention others in a room, and maybe it is useful to let bot know others mentioned the bot in the room. 

##### Problem
When others mentioned bot in a room, let the bot know. 

#### Solution 
when detected the message content contains `@botname `, it will emit `message-at` event(maybe `message-metion` is better)

**Comment by zixia** [comment]
Great start to discuss this.

I'm thinking about just a `mention` event with a `message` parameter. Should always keep it simply & stupid.

Please re-consider your design of this new feature, better to make some discussion with other developers to make the idea better.

**Comment by lijiarui** [comment]
you mean somethin like this? 
``` ts
.on('mention', function(message) {
   // do something
  })
```

**Comment by zixia** [comment]
Yes. 

However, after some time, I feel it's not necessary to have a new event, which just for the message has a particular type.

Maybe we should consider adding a new method `Message.mention()` to identify whether this message is mentioned bot? I'm not sure yet.

**Comment by lijiarui** [comment]
I think you are right, actually, if we add a `mention` event, it looks nothing to do with `message`, and sounds strange, maybe `Message.metion()` is a good way.

But I think it shouldn't be a boolean function.

It should return real message(stripped @bot from the message) if the bot is mentioned and return null if not mentioned.

For example:
If the message is `@bot hello!`, it should return `hello`. 
If the message is `hello!`, it should return `null`

**Comment by zixia** [comment]
I don't agree about the return value in your design.

Because when we design a new method, the params and return values should make sense for the method name, and follow good principles. 

First, I don't think a return value of `string | null` will make sense for who just saw the function name of `mention()`. So I do not like this design.

Second, the following two laws are part of my favorite, for KISS:
1. [Principle of least knowledge(Law of Demeter)](https://en.wikipedia.org/wiki/Law_of_Demeter) Each unit should have only limited knowledge about other units: only units "closely" related to the current unit.
1. [Principle of Least Power](https://www.w3.org/2001/tag/doc/leastPower.html) Choosing the least powerful language suitable for a given purpose.

I will like this design:

```ts
message.mention(): boolean
```

How to strip the bot name from the message, is none of the business of this function.
