### ISSUE TITLE
[help] how to add friend by phone number or wechat id with wechaty bot?

### ISSUE THREAD

**Issue by Samurais** [Chatie/wechaty#319]
# Description
Launch a bot with wechaty, would like to add another person as contact with phone number or wechat id, is it possible to do so now?

**Comment by zixia** [comment]
Sorry, We can't(yet).

That's because Web Wechat does not support doing this in the browser, which means that Wechaty will leak of APIs for adding friend by phone number or wechat id.

Wechaty could do this only after we had implemented the PuppetAndroid/Ios.

If there are any other good ideas to do this, please let me know. Thanks!
