### ISSUE TITLE
run bot in server,about 1 hour ago ,the process will be killed

### ISSUE THREAD

**Issue by yeling584283398** [Chatie/wechaty#330]
I run bot in server,about 1 hour ago ,the process automatic disappear,and have no some log

**Comment by lijiarui** [comment]
#### Need More Information

Sorry, you did not follow the ISSUE Template, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: provide the steps to reproduce the problem.

**Comment by yeling584283398** [comment]
sorry,i did not know the ISSUE Template,I will make some test to get more information about the problem
