### ISSUE TITLE
Support Message Type of Image/Video 

### ISSUE THREAD

**Issue by ak5** [Chatie/wechaty#4]
I couldn't find a way to grab images or other media - any way to do this?

Thanks for this it's quite cool even with just text!

Alex

----------------

### Update by zixia

* wechat4u v0.5 update https://github.com/nodeWechat/wechat4u/commit/5d0275e650572a57ea057c8cb1baff803a253b53
* 语音识别 和 图片特征描述提取 https://github.com/nodeWechat/wechat4u/issues/32

**Comment by zixia** [comment]
@ak5 thanks for like wechaty.

as  you need media support and submit this issue, I'll put this feature as high priority. 💯 

stay tuned.

**Comment by ak5** [comment]
Hi,

Any progress on this?

**Comment by sjdy521** [comment]
能说中文吗…

**Comment by zixia** [comment]
hmm... I'm working on stable issues those weeks to make wechaty run smoothly. will try to finger out how to get media for you tonight. :)

**Comment by zixia** [comment]
@sjdy521 我觉得咱们说中文不太合适。和你聊天应该用 Perl :-]

**Comment by zixia** [comment]
@ak5 how do you think this implementation? video should be easy grabed use the same way.

**Comment by naishstar** [comment]
Hi @zixia bumping this request! Receiving images via message as well as plain text would be awesome! Any idea if you would have time to do this some time soon? The implementation you showed would be perfect.

**Comment by zixia** [comment]
@naishstar 

thanks for bumping! I'm hoping to finish this issue on version 0.5, for supporting receive video/audio and send image/audio/video as well as plain text.

as your request, receiving images via message has already supported in the current code, which you can find at `example/image-bot.ts`, run by `npm run ts-node example/image-bot`. 

you can have a try.

**Comment by zixia** [comment]
so there's only one issue belongs to the milestone v0.5 left... 

it's you! :hocho:

**Comment by zixia** [comment]
There's a media file demo bot in the example directory:

https://github.com/wechaty/wechaty/blob/master/example/media-file-bot.ts

**Comment by tiaozi0912** [comment]
+1. It would be very nice to have this feature.

**Comment by zixia** [comment]
@tiaozi0912 Thanks for pump this up!

In order to support send files(image/video/motion gif/pdf/etc), what we need to do is:

1. Get to know how to call webwxApp `API_webwxuploadmedia` , source code at here: [link](https://github.com/wechaty/webwx-app-tracker/blob/f22cb043ff4201ee841990dbeb59e22643092f92/formatted/webwxApp.js#L795), we can study it from Wechat4U at here: [link](https://github.com/nodeWechat/wechat4u/blob/f9ab10a367ed530e5b1f20a5d95077e57b950db2/src/core.js#L562)
1. Expose a method, ie: `uploadMediaAsync()` for `API_webwxuploadmedia` in WechatyBro around here: [link](https://github.com/wechaty/wechaty/blob/8423c0b22b8c180e21dafd5f2b5cf3a22061769e/src/puppet-web/wechaty-bro.js#L836)
1. add new methods for supporting `uploadMediaAsync` in bridge.ts & puppet-web.ts, examples can be found at [here](https://github.com/wechaty/wechaty/blob/8423c0b22b8c180e21dafd5f2b5cf3a22061769e/src/puppet-web/bridge.ts#L146) and [there](https://github.com/wechaty/wechaty/blob/8423c0b22b8c180e21dafd5f2b5cf3a22061769e/src/puppet-web/puppet-web.ts#L387)
1. modify class `MediaMessage` in message-media.ts, to support add a media stream to message method, like `MediaMessage.addMedia()`(?)
1. modify `PuppetWeb.send()` to support Message with media file.

The list above might not a full list, I'll add new thoughts to this post when I get them in my mind.

It will be great if you could kick it off, and I'll be very happy to follow you and make it works.

**Comment by dcsan** [comment]
Should this be another ticket? Support for images, even without video would be a *very* huge improvement!

**Comment by zixia** [comment]
Split this issue into sub-issues is better because this issue include many feature/functions.

In order to send sticker/image/attachment/video, we need to implement `API_webwxuploadmedia` first. 

Then everything should be easy to implement. :)

**Comment by lbineau** [comment]
Any news for this issue? Wechaty is really convenient but messaging with only plain text, we miss a lot of wechat functionalities. In my opinion this feature is really a must have.

**Comment by zixia** [comment]
@lbineau Thanks for voting this up. :)

**Comment by iRabbit** [comment]
Thanks @mukaiu's work, I can send Image-message right now.

**Comment by zixia** [comment]
Hi all, good news! The pull request to implement send attachment file from @Lockon is just merged to the master branch! This feature will be available after Wechaty v0.7.58. Please submit an issue if you meet any problem or have any suggestions, Cheers!

**Comment by yumewang** [comment]
Can not send(say()) .gif file?
Is someone here? Can you tell me why I can not send .gif? I do like below:
`
let mediaM = new MediaMessage(__dirname + '/test.gif');
room.say(mediaM)
`
but, when I check this message at specified room, I find the message 0KB&undefined(Just use type:APP, 49).  when I sent image(.png, .jpg), that's no any problems? I thought maybe asynchronous processing (Like .gif is not finished, there sent message already)？I have no idea of this.

**Comment by mukaiu** [comment]
@yumewang Fixed,please test PR #438

**Comment by yumewang** [comment]
@mukaiu Thank you firstly.
I have just finished this test. It works totally. 
But there is one issue: **It keeps saying to self, when I got a message, and send a file(.gif).**
![multi-file-send](https://cloud.githubusercontent.com/assets/2267888/25423524/9763549c-2a97-11e7-93a1-c8c2c6c4daff.jpeg)
ps: I used /example/ding-dong-bot.ts to test directly.

**Comment by yumewang** [comment]
@mukaiu can we support to say voice(.mp3 or .amr). I thought this is not be done as you have just changed for saying .gif?

**Comment by d2cs** [comment]
if someone came here while looking for some guide on how to send images using wechaty, 
here is what i have found working for me (npm wechaty no docker), no tscript:


```
const	{ Wechaty }				= require('wechaty')
const 	Room 					= require('wechaty').Room
const 	MediaMessage 			= require('wechaty').MediaMessage

// blablabla login etc

Wechaty.instance({ profile:'bot' })

Room.find({topic:"YourRoomTopic"}).then( room => { **room.say (new MediaMessage('FileName.jpg'))** })
```


if room is defined already, then simply the bold part of it and ofc you may read FileName.jpg from some var.

**Comment by zixia** [comment]
@d2cs Thanks for sharing.

I'd like to make a suggestion:

```diff
const	{ Wechaty, Room, MediaMessage } = require('wechaty')
- const	{ Wechaty }				= require('wechaty')
- const 	Room 					= require('wechaty').Room
- const 	MediaMessage 			= require('wechaty').MediaMessage
```

**Comment by binsee** [comment]
Support for sending any type of file.

doc/pdf/ppt/mp3/mp4/gif/jpg... any type file.

see #714

**Comment by zixia** [comment]
Thanks, @binsee ! 

Finally, this issue seems could be closed in the near future, after 12 months... haha.

**Comment by zixia** [comment]
1. PR from @mukaiu is already landed, and
1. PR from @binsee will be landed recently.

So I closed this issue for keep issue list clean.

Appreciate for the discussion about this feature!
