### ISSUE TITLE
有没有查找好友的方法？

### ISSUE THREAD

**Issue by wangzhipeng404** [Chatie/wechaty#411]
就像itchat的search_friends()那样？

**Comment by zixia** [comment]
Hello, thank you for using Wechaty. 

Issues are about to fire bugs & request features only, so it's not a Support Forum.

To get help, ask questions and discuss with other developers, please join our _Wechaty Developers' Home_ community in Wechat.

### Join Wechaty Developers' Community

Wechaty is used in many ChatBot projects by hundreds of developers. If you want to talk with other developers, just scan the following QR Code in WeChat with secret code _wechaty_, you can join our **Wechaty Developers' Home** at once.

![Wechaty Developers' Home](https://raw.githubusercontent.com/chatie/wechaty/master/image/BotQrcode.png)

Scan now, because other Wechaty developers want to talk with you too! (secret code: _wechaty_)
