### ISSUE TITLE
Contact.findAll with multi wechaty instance

### ISSUE THREAD

**Issue by karboom** [Chatie/wechaty#451]
If I logged N users with N wechaty instance, how can I get friend list of each other?

**Comment by zixia** [comment]
You need to run N Wechaty Instance in different node process(or Docker Container) and use the `Contact.FindAll()` to get all friends.

And in order to communicate between multiple processes, this blog might be useful for you:
<http://blog.chatie.io/2017/04/21/interact-wechaty-with-ruby-on-rails-from-scratch.html>

**Comment by zixia** [comment]
This feature will be supported from v0.16.

See: #518
