### ISSUE TITLE
`Room.findAll()` should always return a `ready()`-ed instance

### ISSUE THREAD

**Issue by cqzhou66** [Chatie/wechaty#477]
## i use Room.findAll()  to get all room,but i found room memberlist is empty in some room.

test code like this:

```
const roomList = await Room.findAll()

for (let i = 0; i < roomList.length; i++) {
    let room = roomList[i]
        if(room.memberList().length<=0){
           log.info('memberList is empty');
        }    
}

```

@lijiarui

**Comment by zixia** [comment]
The reason of got empty memberList is because the data is still not fully loaded from Tencent API Server.

You could:
1. call `room.refresh()` and try again after 1 second
1. use the latest code, and call `memberList()` again if you get an empty result because `memberList()` will call `refresh()` for you.

I think the better way to do this, is to make sure the `Room` is `ready()`-ed before `findAll()` return. 

Any suggestion is welcome.
