### ISSUE TITLE
room-leave监听不到

### ISSUE THREAD

**Issue by lingluo** [Chatie/wechaty#609]
### 监听不到room-leave事件

1. bot.on('room-leave', (w:Wechaty, room:Room, leaverList: Contact[])=>{
        console.log("退出了群聊!");
    })

2.群成员主动离开，event.js文件的onServerMessage方法没有收到回调
3.群主踢人，event.js能收到m.type()==10000。但是，firer.js的解析离开信息时(parseRoomLeave方法)内this==null，导致异常

**Comment by zixia** [comment]
> 2.群成员主动离开，event.js文件的onServerMessage方法没有收到回调

This is duplicated with #63

_can not support this feature because wechat in the web can not detect room member leave(except removed by owner self)._

> 3.群主踢人，event.js能收到m.type()==10000。但是，firer.js的解析离开信息时(parseRoomLeave方法)内this==null，导致异常

Please provide the reproduce steps with the minimum code snip. I believe `this == null` should not happen easily, but if you can reproduce it then it worth to have a look.

**Comment by lingluo** [comment]
thank you for you answer!
this is function image
![wechatimg1320](https://user-images.githubusercontent.com/1208065/27570975-daf64728-5b34-11e7-83a9-d461bd9f8bea.jpeg)

**Comment by zixia** [comment]
Could you please provide the minimal code snip to reproduce this problem? Or we can not know what's happen, then we can not debug it.

**Comment by lingluo** [comment]
[test.zip](https://github.com/Chatie/wechaty/files/1107542/test.zip)

**Comment by zixia** [comment]
Your code seems should be ok.

You could try to let the bot join a room then quit it, I believe it should work as expetect.
