### ISSUE TITLE
Heroku Error Info by Wechaty

### ISSUE THREAD

**Issue by paulwan** [Chatie/wechaty#628]
It's " Heroku Error " when I want to use wechaty in heroku buttons.

I mean [this page](https://elements.heroku.com/buttons/zixia/wechaty)

My heroku was display the error info: 
```
The content of app.json is not valid; please see app.json Schema for more information.
• name: is too long (maximum is 30 characters)
```

did your have plan to fix it ? and How could I use Wechaty on heroku?

**Comment by zixia** [comment]
Hi paulwan,

Thanks for trying the Heroku deploy button.

I had just fixed the name Schema in `app.json`, please see the related commit.

However, this button is in the very alpha stage on the PhantomJS head of Wechaty.

Today I'm not sure if PhantomJS could still work because we are using Chrome only in the past six months. There's an issue about this at <https://github.com/Chatie/wechaty/issues/60>, you could have a look at it and try PhantomJS as you like.

Any suggestion will be welcome and if you want to contribute to making Heroku work, I could provide more information for you.

Have a good weekend!

**Comment by paulwan** [comment]
Okey, Thank you fix commit. I'm a newbie and learning to Wechaty, I'll try to use it by Coffeescript2.  hope bring some valuable information to you.
