### ISSUE TITLE
what I need is just a lib instead of a product

### ISSUE THREAD

**Issue by nbwsc** [Chatie/wechaty#709]
缺少自由度

**Comment by zixia** [comment]
Wechaty is an NPM Module with simple APIs that helps you get the bot job done.

What is the reason makes you think Wechaty is a "product" instead of a "lib", have you tried `npm install wechaty`?

**Comment by zixia** [comment]
Hello, could you please tell me why do you think Wechaty is a _PRODUCT_ instead a _LIBRARY_? 

Because I'd like to know what others think about Wechaty, especially from an engineer/entrepreneur.

**Comment by nbwsc** [comment]
你好zixia,我不得不说docker很棒，ts很棒。我想要一个轻量稳定的对微信网页接口的封装库。`Wechaty`是被封装成单例的，实例化以后默认会开启`Browser Driver`然而API文档对这块描述也不是很详细,`npm install wechaty`也会下载一些我其实用不到的东西。我对比了几个微信机器人框架，感觉还是基于itchat的wxpy好用一点.但是最近发现一个问题，就是用wxpy容易导致账号网页接口被封，现象就是无法登陆微信网页版。不知道使用Wechaty的同学有没有被封的情况?

**Comment by zixia** [comment]
Thank you for the explanation. I heard that you are praising the Docker and TypeScript, it would be fantastic if you could also praise Wechaty, too. ;-]

I agree Wechaty is some kind of heavy because it based on WebDriver. It's by design, which means we have to trade between the Pros and Cons.

If you need some light weight wechat bot library in javascript, I would like to recommend Wechat4U project. It could be run both under Node.js and Browser environment, with very few dependencies.

About the bot blocking problem, please See: #603

**Comment by nbwsc** [comment]
我几乎看遍了所有关于帐号被封的issue，感觉这是一个比较严重的问题。微信似乎在打击这种hack api的方式。所以我在想这种使用`web driver`的方式是不是更安全一点呢？或者甚至直接用`puppeteer`操作dom的方式来做，这种“外挂”的形式是不是能把帐号被封的可能性降到最低？

**Comment by zixia** [comment]
Yes, WebDrive and high-level UI operation should be "better", but only better a little bit. It can not prevent the bot from being blocked.

Because I think the Tencent is using the behavior pattern to identify which one is the bot and which one is human, no matter than how you connect to the server. A very simple neural network should be able to do that binary classification very easy.

I'd like to suggest you join the Wechaty Developer Community wechat group. There have many developers inside and we are talking about this a lot in every day.

**Comment by nbwsc** [comment]
👍

**Comment by gold3bear** [comment]
用PC机器人好些，有些网上易语言的源码hook了微信的PC版

**Comment by nbwsc** [comment]
windows版吗? 我现在采用android的Xposed感觉还可以

**Comment by zixia** [comment]
Glad to know that you guys are using Win32 & Android Hook, which I'm also very interested in.

Would you like to share your experience & technologies of what you did on the ChatBot(i.e., what did you do, how did you control, etc.) to the Wechaty community? Because that would help others to know more about the different methods of controlling Wechat ChatBots.

I would also like to send a blog invitition to you if you could post a blog post on Chatie blog. Thanks! @gold3bear @nbwsc

**Comment by nbwsc** [comment]
@zixia talk to you on wechat
