### ISSUE TITLE
MediaMessage.ext() cannot work as expect

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#721]
### Expected behavior
Trying to get file extension using MediaMessage.ext()

### Actual behavior
Can get picture extension but cannot get other file extensions, such as pdf.

### Steps to reproduce the behavior (and fixes, if any)
code as follows:

```ts
 .on('message', async function (m) {
    if (m.self()) {
      return
    }
    if (m.rawObj && m.type() === MsgType.APP) {
      console.log('======get m.ext()=======')
      const mediaMsg = new MediaMessage(m.rawObj)
      console.log(mediaMsg.ext())
    }
```

#### if I send a picture:
logs as follows:
```
======get m.ext()=======
jpg
```

#### if I send a pdf file
log as follows:
```
======get m.ext()=======
(node:55232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: not support type: 49
(node:55232) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lijiarui** [comment]
I pass url parameter as follows, it gets the totally opposite result：
```ts
 .on('message', async function (m) {
    if (m.self()) {
      return
    }
    if (m.rawObj) {
      console.log('======get m.ext()=======')
      const mediaMsg = new MediaMessage((m as any).obj.url)
      console.log(mediaMsg.ext())
    }
```

#### If I send a picture:
log as follows:
```
======get m.ext()=======
(node:56351) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: not support type: undefined
(node:56351) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### If I send a pdf file：
log as follows:
```
======get m.ext()=======
pdf&fromuser=3116474446&pass_ticket=OfQmsmw%252BNjthyjL2NZrP8%252FUAlFZDe7mGP1UjvS7EdRnFjdmDwtj9RwyJRAXNfWPc&webwx_data_ticket=gSdEUgDwMxhFL9uQN8ZamEUG
```

**Comment by zixia** [comment]
Hello, thank you for using Wechaty. 

Issues are about to fire bugs & request features only, so it's not a Support Forum.

To get help, ask questions and discuss with other developers, please join our _Wechaty Developers' Home_ community in Wechat.

### Join Wechaty Developers' Community

Wechaty is used in many ChatBot projects by hundreds of developers. If you want to talk with other developers, just scan the following QR Code in WeChat with secret code _wechaty_, you can join our **Wechaty Developers' Home** at once.

![Wechaty Developers' Home](https://raw.githubusercontent.com/chatie/wechaty/master/image/BotQrcode.png)

Scan now, because other Wechaty developers want to talk with you too! (secret code: _wechaty_)
