### ISSUE TITLE
chrome-headless support

### ISSUE THREAD

**Issue by htoooth** [Chatie/wechaty#739]
Now, chrome support headless mode. It can run without Xvfb lib. I advise that the wechaty project should move from phantomjs to chrome-headless. 

There are some projects to referred.

1. [puppeteer](https://github.com/GoogleChrome/puppeteer)
2. [chromeless](https://github.com/graphcool/chromeless)

**Comment by zixia** [comment]
That's awesome, Thank you very much for the suggestion!

The chrome headless mode will make the infrastructure of Wechaty become more simple and easy to setup. I'd like to switch to that.

Will dive into it when I have time, and PR is welcome!

**Comment by zixia** [comment]
After implementing the headless chrome, I found that we have to wait until the chrome V62 to be stable, because when we are using `--headless` args, chrome will not allow self signed certificate to be used when visiting https://localhost.

See: <https://bugs.chromium.org/p/chromium/issues/detail?id=721739#c26>

**Comment by zixia** [comment]
Wechaty version v0.8.148 or above can enable Chrome headless mode by setting the env with `WECHATHY_HEAD=chrome-headless`
