### ISSUE TITLE
got invalid driver at ttl 0

### ISSUE THREAD

**Issue by cmzz** [Chatie/wechaty#749]
version: 0.8.165

运行出错。

```
this.bot = Wechaty.instance({
      // 'head': 'phantomjs'
    })
```

log：
 ```
 [10:53:00:0665] [error] Bot error: %s Error: got invalid driver at ttl 0
      at BrowserDriver.<anonymous> (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/wechaty/src/puppet-web/browser-driver.ts:185:21)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

![image](https://user-images.githubusercontent.com/6111715/29501990-511d7d4e-85f2-11e7-9b02-df420b24c9a8.png)

请问下有在产品中使用 wechaty 的案例吗? 我现在很崩溃啊，用户频繁的反映微信登录不上，掉线..

这几天在 windows server 上运行， 启动后 10次有  9次都报 Error: got invalid driver at ttl 0 错误。
侥幸登录成功后，1小时我在登陆服务器上去看时，已经掉线了。

@zixia 心好累

**Comment by zixia** [comment]
Sorry for hearing that the PhantomJS is not working well.

PhantomJS is almost no one use it, we are all using Chrome, with the Docker solution. I do not know it could work until you tell me that.

So my suggestion is: **to use the Docker solution**. It works without any problem and is used by many developers in their production environment.

----------------------------

About your issue, I think you need to run `npm install phantomjs-prebuilt --save` in your project.

Because I had removed the default `phantomjs-prebuilt` dependencies from wechaty in the recent version.

See: #385 #1 https://github.com/Chatie/wechaty/issues/743#issuecomment-323246498

**Comment by zixia** [comment]
Suggestion 1: use Docker solution.
Suggestion 2: go to Wechaty Developer Community group to find someone using Windows platform, and ask for help from him/her.
